### ISSUE TITLE
Blocked with PC host app and EPDiy V6 PCB

### ISSUE THREAD

**Issue by martinberlin** [amadeok/Epdiy-Eink-PC-monitor#2]
Hi Amadeo,

Really nice project!
I compiled the client without problems. And now I have the issue that is not sending anything to the display from the PC host app.
This is my log for the PC host app:

```
$ python screen_capture.py example_display.conf
esp32_ip_address: 192.168.12.163
display id: 1
refresh_every_x_frames: 100
do_full_refresh: 30
framebuffer_cycles: 4
enable_skipping: 0
epd_skip_threshold: 75
esp32_multithread: 0
framebuffer_cycles_2: 4
framebuffer_cycles_2_threshold: 76
selective_compression: 90
nb_chunks: 5
nb_draws: 2
draw_white_first: 1
mode: 5
draw_rmt_times:  250  100  250  250  
wifi enabled 
current working directory is: /home/martin/Documents/C/Epdiy-Eink-PC-monitor-optimize/pc_monitor/pc_host_app
Connected to esp wifi

new pipe size: 1048576
Opening pipes...
Pipes opened
C++ ID 1 mirroring started 
color 1.0, contrast  2.0  brightness 1.0, sharpness 1.0,  grey_to_monochrome_threshold 200
Display ID: 1, capture took 1431ms
-1 
warning ready2 per_frame_wifi_settings dif 
0 
warning ready2 per_frame_wifi_settings dif 
-1 
warning ready2 per_frame_wifi_settings dif 
-1 
warning ready2 per_frame_wifi_settings dif 
-1 
warning ready2 per_frame_wifi_settings dif 
-27 
warning ready2 per_frame_wifi_settings dif 
Processing time 181ms
```

As an additional info, the log on the epdiy client side
```
I (10653) pc_monitor: Socket accepted ip address: 192.168.12.106
Powering on Epdiy board 
 epd_poweron 
EPD clear took 1056ms.
Receiving settings.. 
settings_size 28 
### Settings ### 28 
framebuffer_cycles 4 
enable_skipping 0 
epd_skip_threshold 75 
esp32_multithread 0 
framebuffer_cycles_2 4 
framebuffer_cycles_2_threshold 76 
draw_white_first 1 
selective_compression 90 
nb_chunks 5 
nb_draws 2 
per_frame_wifi_settings_size 14 
nb_rmt_times 4 
################# 
sizes 78809 
I (12066) pc_monitor: nb_chunks 5, nb_rows_chunks 151, chunk_size 38809, eink_framebuffer_size 194048, chunk_size+extra_bytes 78809
Download and extract took : 77
Draw time: 109
d clearing with delay 255
```

Note: It was giving me an error before, since it needed this also to be installed  **pip install opencv-contrib-python**
Any hint on what I'm doing wrong? The IDF epdiy client receives something, since the screen wakes up, but it shows only white pixels.
I could see only one frame of a quite distorted screen ;)
![D79ADE43-8365-45B7-A37D-5E2368DABF78](https://user-images.githubusercontent.com/2692928/152049358-0607815b-9e46-49fd-9dba-d4296407305b.jpeg)

**Comment by martinberlin** [comment]
I have more signs of what is going on here. I think the issue is that I was trying this with a V6 board. With Lilygo 4.7 that uses the old version of EPDiy seems to work. Any clues if I can update it to work also with v6?

**Comment by amadeok** [comment]
> I have more signs of what is going on here. I think the issue is that I was trying this with a V6 board. With Lilygo 4.7 that uses the old version of EPDiy seems to work. Any clues if I can update it to work also with v6?

Hey 
Yes incompatibility between the a newer version of the epdiy software and our PC application seems to be the problem. 
From what i see the board screen receives the first frame but it is sort of broken and shifted as you can see, this is most likely that the board is set to receive a framebuffer of a resolution different than the one the pc app is sending, which in turns causes it to expect a wrong number of bytes from the wifi transfer, and then causes that error you see in the pc app console, and the the board to hang after the first received framebuffer.
The pc app sends an array of 6 bytes each frame to the board and the board sends it back to the pc app and when they don't match it gives that error: "warning ready2 per_frame_wifi_settings dif" (sorry for the obscure choice of words).

I would check the following: are you sure you set up the correct resolution of the display in the .conf file?

If that's not the problem then it's probably a bug and I'll see if i can take a look at it with the debugger this week-end.

**Comment by amadeok** [comment]
Please also tell me which boards revisions you have tested and with which displays
cheers

**Comment by martinberlin** [comment]
Sure I used:

ED060XC3 | 6" | 758 x 1024.  Width 1024 height 758

I think that is the right resolution. Display is working correctly with the EPDiy demos, note I see some text on the top “Terminal”, etc so orientation seems correct.

**Comment by amadeok** [comment]
> Sure I used:
> 
> ED060XC3 | 6" | 758 x 1024. Width 1024 height 758
> 
> I think that is the right resolution. Display is working correctly with the EPDiy demos, note I see some text on the top “Terminal”, etc so orientation seems correct.

Hello
I just tested the latest repositories and everything seems to work fine with the v4 and v5 board software and your display, however when i set it to v6 i get compile errors and i'm not able to flash. That could be because i'm using a esp32 development board as i only have v4 boards right now.
Please post the .conf file you are using with screen_capture.py

**Comment by martinberlin** [comment]
Sure I will check tomorrow In detail but the .conf is the same as default except with 1024 as width and 768 as height. If you have time on the weekend we could even do a short screen share with teamviewer or similar and I can show you everything.

**Comment by amadeok** [comment]
> Sure I will check tomorrow In detail but the .conf is the same as default except with 1024 as width and 768 as height. If you have time on the weekend we could even do a short screen share with teamviewer or similar and I can show you everything.

Yes we can do that also. What version of linux are you using? I'm trying with ubuntu 18.04 and with the latest esp-idf i couldnt compile anything, i had to use 4.3 , but still i couldnt compile the mirroring program for the board when configured for v6 board.

**Comment by martinberlin** [comment]
Hi Amadeo, exactly same setup here Ubuntu 20 and $ idf.py --version
ESP-IDF v4.3

What are exactly the compile errors you are getting?

**Comment by amadeok** [comment]
> 

Hello i  was able to compile in the end, but i couldn't replicate the bug. Are you sure you are using the lastest versions of both the pc host program and the program for the board?

**Comment by martinberlin** [comment]
yes sure. same version worked perfectly with Lilygo EPD47. if you want tomorrow we can check it out together, my email you can find in github profile

**Comment by martinberlin** [comment]
Amadeo, after pulling your last update I'm getting this

```
$ python screen_capture.py 
Traceback (most recent call last):
  File "screen_capture.py", line 2, in <module>
    from utils import *
  File "/home/martin/Documents/C/Epdiy-Eink-PC-monitor-optimize/pc_monitor/pc_host_app/utils.py", line 936, in <module>
    ctx = display_list[0]
IndexError: list index out of range
```

Bue later it just run again. It's like for some reason at some point Python could not list my displays.
